services:
  redis:
    image: redis:alpine
    container_name: bioflow_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: bioflow_api
    ports:
      - "8080:8080" 
    volumes:
      - ./workspace:/app/workspace
      - /var/run/docker.sock:/var/run/docker.sock 
    working_dir: /app
    environment:
      - REDIS_ADDR=redis:6379
      - HOST_WORKSPACE=${PWD}/workspace
    command: ["./pipeline", "-mode", "server"] 

  worker:
    build: .
    container_name: bioflow_worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/app/workspace
    working_dir: /app
    environment:
      - REDIS_ADDR=redis:6379
      - HOST_WORKSPACE=${PWD}/workspace
    depends_on:
      - redis
      - api
    command: ["./pipeline", "-mode", "worker"]

volumes:
  redis_data: